### ISSUE TITLE
Man kan flyve igennem planeten

### ISSUE THREAD

**Issue by Simon9877** [DDU-Spiludviklingsprojektet/Spiludviklingsprojekt#18]

**Comment by Simon9877** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/DDU-633abb9aad5cb90f9cfab26f/issues/DDU-Spiludviklingsprojektet/Spiludviklingsprojekt/18?planning-poker) with Zenhub @rkarmark

**Comment by rkarmark** [comment]
Need more detailed descripiton of when this is happening, reopen with better documentation
